In [1]:
!pip install numpy pandas

Requirement already satisfied: numpy in c:\users\vishal\appdata\local\programs\python\python310\lib\site-packages (2.2.6)
Requirement already satisfied: pandas in c:\users\vishal\appdata\local\programs\python\python310\lib\site-packages (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vishal\appdata\roaming\python\python310\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\vishal\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\vishal\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\vishal\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import numpy as np
import pandas as pd

In [3]:
movies=pd.read_csv('tmdb_5000_movies.csv')
credits=pd.read_csv('tmdb_5000_credits.csv')

In [51]:
credits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4803 non-null   int64
 1   title     4803 non-null   object
 2   cast      4803 non-null   object
 3   crew      4803 non-null   object
dtypes: int64(1), object(3)
memory usage: 150.2+ KB

In [5]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [6]:
movies=movies.merge(credits,on='title')

In [7]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [8]:
# genre id keyword title overview cast crew
movies=movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [9]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [10]:
movies.dropna(inplace=True)

In [11]:
movies.duplicated().sum()

np.int64(0)

In [12]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [13]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [14]:
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
       L.append(i['name'])
    return L

In [15]:
movies['genres']=movies['genres'].apply(convert)

In [16]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [17]:
movies['keywords']=movies['keywords'].apply(convert)

In [18]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [19]:
def convert1(obj):
    L=[]
    c=0
    for i in ast.literal_eval(obj):
        if c!=3:
            L.append(i['name'])
        else:
            break    
    return L

In [20]:
movies['cast']=movies['cast'].apply(convert1)

In [21]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [22]:
movies['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [23]:
def fetch_director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            L.append(i['name'])
            break   
    return L

In [24]:
movies['crew']=movies['crew'].apply(fetch_director)

In [25]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [26]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [27]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [28]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [29]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton]

In [30]:
movies['tag']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [31]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tag
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [32]:
new_df=movies[['movie_id','title','tag']]

In [33]:
new_df['tag']=new_df['tag'].apply(lambda x:" ".join(x))

C:\Users\VISHAL\AppData\Local\Temp\ipykernel_31312\4079141722.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tag']=new_df['tag'].apply(lambda x:" ".join(x))

In [34]:
new_df['tag']=new_df['tag'].apply(lambda x:x.lower())

C:\Users\VISHAL\AppData\Local\Temp\ipykernel_31312\1740795540.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tag']=new_df['tag'].apply(lambda x:x.lower())

In [35]:
new_df

,movie_id,title,tag
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."
...,...,...,...
4804,9367,El Mariachi,el mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,a newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,when ambitious new york attorney sam is sent t...
4808,25975,My Date with Drew,ever since the second grade when he first saw ...

In [36]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [37]:
vectors=cv.fit_transform(new_df['tag']).toarray()

In [38]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4806, 5000))

In [39]:
print(cv.get_feature_names_out())

['000' '007' '10' ... 'zoo' 'zooeydeschanel' 'zoëkravitz']

In [40]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\vishal\appdata\local\programs\python\python310\lib\site-packages (3.9.3)
Requirement already satisfied: click in c:\users\vishal\appdata\local\programs\python\python310\lib\site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in c:\users\vishal\appdata\local\programs\python\python310\lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\users\vishal\appdata\local\programs\python\python310\lib\site-packages (from nltk) (2026.2.28)
Requirement already satisfied: tqdm in c:\users\vishal\appdata\local\programs\python\python310\lib\site-packages (from nltk) (4.67.3)
Requirement already satisfied: colorama in c:\users\vishal\appdata\local\programs\python\python310\lib\site-packages (from click->nltk) (0.4.6)

In [41]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [42]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [43]:
new_df['tag']=new_df['tag'].apply(stem)

C:\Users\VISHAL\AppData\Local\Temp\ipykernel_31312\599176683.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tag']=new_df['tag'].apply(stem)

In [44]:
from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(vectors)

In [45]:
def recommend(movie):
    movie_index=new_df[new_df['title']==movie].index[0]
    distance=similarity[movie_index]
    movies_list=sorted(list(enumerate(distance)),reverse=True,key=lambda x:x[1])
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [46]:
recommend('Batman Begins')

Batman Begins
The Dark Knight
The Dark Knight Rises
Amidst the Devil's Wings
Batman
Batman & Robin
Batman
Mi America
Defendor
Dead Man Down
Batman v Superman: Dawn of Justice
Batman Returns
Teenage Mutant Ninja Turtles
Batman Forever
Nighthawks
Nine Queens
Brick Mansions
Hobo with a Shotgun
City By The Sea
Gangster's Paradise: Jerusalema
The Green Hornet
The Yards
Rampage
Walking Tall
Easy Money
10th & Wolf
Menace II Society
Rockaway
The Godfather
The Taking of Pelham 1 2 3
The Punisher
The Devil's Double
Now You See Me 2
Sexy Beast
Donnie Brasco
My Super Ex-Girlfriend
Kick-Ass 2
The Spirit
Wicked Blood
Sugar Hill
Punisher: War Zone
RockNRolla
I Am Wrath
Perrier’s Bounty
Jimmy and Judy
The Shawshank Redemption
The Usual Suspects
Harsh Times
Shooter
Righteous Kill
Wanted
Kiss of Death
Nightcrawler
Superman
Raising Helen
Taxi Driver
Sherlock Holmes: A Game of Shadows
Bon Cop Bad Cop
Batman: The Dark Knight Returns, Part 2
A Most Violent Year
Better Luck Tomorrow
Hitman
Lucky Number Slevin
Double Jeopardy
Dom Hemingway
Kick-Ass
Street Fighter: The Legend of Chun-Li
Bottle Rocket
Bound by Honor
Timecop
Drive Hard
The Place Beyond the Pines
Deadline - U.S.A.
Sin City
The Death and Life of Bobby Z
Code of Honor
The Masked Saint
Deuces Wild
Taken 2
Blood Ties
Cheap Thrills
The First Great Train Robbery
The Transporter Refueled
Miss Congeniality
Synecdoche, New York
Class of 1984
The Siege
Dick Tracy
The Prestige
Summer of Sam
The Baader Meinhof Complex
Romeo Is Bleeding
The Way of the Gun
American Psycho
Adulterers
Catwoman
Capote
2 Guns
The Godfather: Part II
Premium Rush
The Crew
Mad Money
The American
Find Me Guilty
Dutch Kills
Safe
Half Past Dead
Michael Clayton
Harry Brown
The Fighter
Point Break
Boys Don't Cry
In Too Deep
L.A. Confidential
TMNT
The Net
Out of the Furnace
Iron Man 2
The Good Thief
Man of Steel
Megamind
Mercury Rising
American Hustle
Once Upon a Time in America
Dark Blue
The Sting
The Jerky Boys
Exiled
Changing Lanes
Dancer in the Dark
The Sweeney
The Phantom
In the Name of the King III
Real Women Have Curves
Man on Fire
The Infiltrator
Gridiron Gang
Crouching Tiger, Hidden Dragon
The Patriot
The Next Three Days
Collateral
West Side Story
Life or Something Like It
The Last House on the Left
Young Guns
Dum Maaro Dum
The Departed
Ninja Assassin
The Shadow
Stolen
United 93
Point Blank
There's Always Woodstock
Mississippi Mermaid
Special
Deadfall
The Replacement Killers
Checkmate
Archaeology of a Woman
Road to Perdition
The Other Guys
The Fast and the Furious: Tokyo Drift
RED
Metropolis
Freeze Frame
Edge of Darkness
Superman II
Casino
Rush
Laws of Attraction
Elite Squad
Let's Go to Prison
Harper
The Betrayed
Last I Heard
Fair Game
Get Carter
Machine Gun McCain
Contraband
Harvard Man
The Specials
Astro Boy
The Equalizer
Midnight in the Garden of Good and Evil
Madea's Witness Protection
Casino Jack
Superman Returns
The Gunman
Superman III
Narc
American Ninja 2: The Confrontation
Krull
Seven Psychopaths
Mutual Friends
The Glimmer Man
The Perfect Host
RoboCop
Enemy of the State
Dredd
Prison
I Am Legend
Fantastic Four
Deliver Us from Evil
Undisputed
Death Sentence
The Legend of Tarzan
A Walk Among the Tombstones
Don't Be Afraid of the Dark
The World's Fastest Indian
Drive
10 Days in a Madhouse
Trash
Mr. Nice Guy
Headhunters
Dead Man's Shoes
Down Terrace
The Circle
Green Lantern
Cop Land
Atlas Shrugged Part III: Who is John Galt?
This Is England
The Lives of Others
Nurse Betty
The Spanish Prisoner
Winnie Mandela
Frances Ha
Love Me Tender
Echo Dr.
Iron Man
Kill Bill: Vol. 1
Disclosure
Get Rich or Die Tryin'
J. Edgar
Code Name: The Cleaner
Plastic
Four Single Fathers
Batman
The Wolf of Wall Street
Shaft
The Trials Of Darryl Hunt
Starsky & Hutch
Deadpool
Whiteout
The Whole Nine Yards
Witness
The Fast and the Furious
The Incredibles
Pride and Glory
Steel
London Has Fallen
Romeo Must Die
Kansas City
White Oleander
Open Road
Metropolitan
Blue Ruin
Bronson
Baby Boy
Lilya 4-ever
Gun Shy
Ip Man 3
Rumble in the Bronx
Chicago Overcoat
Big Mommas: Like Father, Like Son
Suicide Squad
Apocalypto
Black Water Transit
3 Days to Kill
The Last Station
Renaissance
B-Girl
Madea Goes to Jail
Saw III
Spring Breakers
Jesus' Son
The Toxic Avenger
Tsotsi
The Incredible Hulk
The Day After Tomorrow
Charlie's Angels
Changeling
Panic Room
3 Ninjas Kick Back
Holy Motors
Inside Out
The Promise
The River Wild
Chicago
Dope
I Am Number Four
Colombiana
Sabotage
Stone Cold
RoboCop 3
True Romance
King's Ransom
Butterfly on a Wheel
Broken Horses
The Oxford Murders
Midnight Cowboy
Silver Medalist
The Lady from Shanghai
Quinceañera
15 Minutes
Speed Racer
2 Fast 2 Furious
xXx: State of the Union
Money Train
Training Day
We Own the Night
The Man
Blood Done Sign My Name
Awake
Go
Sinister
N-Secure
American Gangster
Up
Bruce Almighty
Captive
Sherlock Holmes
The Hunted
Basic
Prisoners
Cellular
City Hall
Heist
Superhero Movie
Teenage Mutant Ninja Turtles II: The Secret of the Ooze
Split Second
Water & Power
X-Men: First Class
Hulk
Con Air
Tango & Cash
The Thomas Crown Affair
Mean Streets
Operation Chromite
Swelter
Tower Heist
Payback
Bless the Child
The Conspirator
The Best Offer
Witless Protection
Last Action Hero
Unleashed
The Matador
Auto Focus
Rent
Need for Speed
Smilla's Sense of Snow
Carlos
A Better Life
Green Street Hooligans: Underground
The Orphanage
Lethal Weapon 4
Parker
Antitrust
Blood and Wine
The Grey
Kiss of the Dragon
All Good Things
Observe and Report
The Skulls
Shinjuku Incident
Vera Drake
Action Jackson
Zipper
Batman
Ant-Man
The Bucket List
Pain & Gain
Copying Beethoven
The Wolverine
X-Men
Blood Work
Henry V
Aloft
Brigham City
Fantastic 4: Rise of the Silver Surfer
S.W.A.T.
The Italian Job
Malibu's Most Wanted
The Amazing Spider-Man 2
Brooklyn's Finest
Savages
The French Connection
Save the Last Dance
Birthday Girl
Brighton Rock
Maria Full of Grace
Next Day Air
Closer to the Moon
Stories of Our Lives
Face/Off
Undercover Brother
Cradle 2 the Grave
El Rey de Najayo
Run All Night
Focus
Young Sherlock Holmes
Getaway
Ernest & Celestine
Civil Brand
Cold Mountain
3:10 to Yuma
Superman IV: The Quest for Peace
Betty Fisher and Other Stories
City of God
Teenage Mutant Ninja Turtles: Out of the Shadows
Transcendence
The Informant!
The Funeral
The Boondock Saints II: All Saints Day
The Toxic Avenger Part II
The 51st State
Lone Wolf McQuade
Firestorm
Bandits
Dolphin Tale 2
Prom Night
In Cold Blood
Close Range
American Splendor
Butterfly
Rush Hour 3
Jack Reacher
Assassins
The Mask
The Godfather: Part III
The International
The Adventures of Ford Fairlane
Patriot Games
The Rainmaker
Transporter 2
The Immigrant
The Loss of Sexual Innocence
The World Is Mine
The Amazing Spider-Man
Inception
Blackhat
Vantage Point
Big Momma's House 2
Snakes on a Plane
The Wicked Lady
As It Is in Heaven
The Gambler
12 Rounds
Match Point
The Square
Slam
The Score
Hannibal Rising
Femme Fatale
The New World
Machine Gun Preacher
Corky Romano
Stand by Me
Brooklyn Rules
The Singing Detective
Shame
Frenzy
D.E.B.S.
Stonewall
Nine Dead
Donkey Punch
The Girl with the Dragon Tattoo
The Devil's Own
The Bourne Identity
The Thief and the Cobbler
Sicario
Kung Fu Jungle
The Man Who Knew Too Little
The Killer Inside Me
Paper Towns
A Low Down Dirty Shame
Crocodile Dundee
The Ice Storm
X-Men Origins: Wolverine
Babe: Pig in the City
Perfume: The Story of a Murderer
The Lego Movie
Chappie
Lethal Weapon 3
Exit Wounds
Out of Africa
Vanity Fair
Coriolanus
Partition
Set It Off
Velvet Goldmine
The Losers
Raise Your Voice
We Have Your Husband
The Duchess
Zulu
End of Watch
Criminal Activities
Ghost Dog: The Way of the Samurai
The Blue Room
Hits
Confidence
Wild Target
Shin Godzilla
Hancock
Now You See Me
The Truman Show
Blade
Harley Davidson and the Marlboro Man
Machete Kills
One Direction: This Is Us
Peaceful Warrior
Dead Like Me: Life After Death
The Hunt
Super
Redemption Road
I Love Your Work
Blue Like Jazz
Straight Out of Brooklyn
Spider-Man 2
Die Hard: With a Vengeance
The General's Daughter
Urbania
Duplicity
Memoirs of an Invisible Man
Side Effects
The Raven
Freedom Writers
Trance
Only God Forgives
Heli
Gangs of New York
Austin Powers in Goldmember
21 Jump Street
Quantum of Solace
Taken 3
Sleepers
The Newton Boys
Lakeview Terrace
No Good Deed
Step Up
Sparkle
A Cock and Bull Story
Cure
Mission: Impossible III
The Long Kiss Goodnight
Black Mass
Non-Stop
Chasing Liberty
Killing Them Softly
Girl with a Pearl Earring
Kit Kittredge: An American Girl
Red Riding: In the Year of Our Lord 1974
Elektra
Chain Reaction
Bullet to the Head
The Cotton Club
Bodyguards and Assassins
Secret in Their Eyes
We're No Angels
Faithful
September Dawn
Hav Plenty
Takers
Frequency
Confessions of a Dangerous Mind
Armored
My Dog Skip
Watchmen
Dream House
Death to Smoochy
8MM
Snowpiercer
Southpaw
Kiss the Girls
In the Valley of Elah
The Animal
Street Kings
A Scanner Darkly
A Simple Plan
Fur: An Imaginary Portrait of Diane Arbus
Pulp Fiction
Wuthering Heights
The Protector
Mozart's Sister
Frozen River
Kids
The Basket
Pieces of April
All That Jazz
The Lincoln Lawyer
The Express
P.S. I Love You
Wild
Phone Booth
Brooklyn
Motherhood
Shattered Glass
Made
Boynton Beach Club
Lage Raho Munna Bhai
The Green Inferno
Pink Flamingos
Autumn in New York
Home Alone 2: Lost in New York
The Son of No One
El Mariachi
Micmacs
Public Enemies
Beverly Hills Cop III
Along Came a Spider
The Big Hit
Party Monster
Exodus: Gods and Kings
Hostage
Flightplan
16 Blocks
Identity Thief
Alex Cross
The Shipping News
Mystic River
Virtuosity
Runner Runner
Agent Cody Banks 2: Destination London
Original Sin
The Libertine
In Bruges
Attack the Block
The Life Before Her Eyes
Boiler Room
Skin Trade
The Dead Girl
Griff the Invisible
London
Sands of Iwo Jima
Compliance
Malevolence
Me You and Five Bucks
Eastern Promises
Silverado
The Bad Lieutenant: Port of Call - New Orleans
The Quiet American
Radio Days
A Thin Line Between Love and Hate
The Last Temptation of Christ
A Fine Step
The Legend of Hercules
Killing Zoe
All the King's Men
The Naked Gun 33⅓: The Final Insult
Beverly Hills Cop II
The Cookout
Pandaemonium
Volver
Anomalisa
The Blood of Heroes
Airlift
Queen of the Mountains
The Hebrew Hammer
The Helix... Loaded
The Sticky Fingers of Time
Butterfly Girl
This Is Martin Bonner
Kingdom of Heaven
Surrogates
Domino
Child 44
The Pelican Brief
Lord of War
Blindness
Me and Orson Welles
Coco Before Chanel
The Best Man
Salvation Boulevard
Requiem for a Dream
Please Give
Buffalo '66
Napoleon Dynamite
The Negotiator
Hackers
Looper
After the Sunset
Inside Man
Absolute Power
The Grandmaster
Beverly Hills Cop
Shade
Traffic
Scarface
The Huntsman: Winter's War
Alvin and the Chipmunks: The Road Chip
Entrapment
The Hateful Eight
Domestic Disturbance
I Dreamed of Africa
Appaloosa
Red Sonja
Wasabi
The Iceman
Taxman
Welcome Home Roscoe Jenkins
Shakespeare in Love
From Dusk Till Dawn
The Exorcism of Emily Rose
Trust
Flame & Citron
Thor
Dracula Untold
Annie
All the Pretty Horses
The Mechanic
The Three Burials of Melquiades Estrada
The Caveman's Valentine
Celebrity
25th Hour
In the Bedroom
Hurricane Streets
The Bourne Legacy
Lara Croft Tomb Raider: The Cradle of Life
Kangaroo Jack
Mad City
The Pledge
Curse of the Golden Flower
Bandidas
Paparazzi
Adaptation.
The White Ribbon
The Young Messiah
Highlander
Slow Burn
Idlewild
House of Flying Daggers
High Heels and Low Lifes
After.Life
The Night Listener
An Everlasting Piece
London to Brighton
Kill List
Mutual Appreciation
How to Train Your Dragon 2
Mr. & Mrs. Smith
Raise the Titanic
Son of God
Wild Things
Three Kingdoms: Resurrection of the Dragon
Sea of Love
Running Scared
Kabhi Alvida Naa Kehna
Mad Max Beyond Thunderdome
Kites
Desert Dancer
Letters to God
A True Story
Rush Hour 2
Sky Captain and the World of Tomorrow
The Sum of All Fears
Se7en
Akeelah and the Bee
The Crying Game
Monsters
Rust
Red Dragon
The Life of David Gale
Wild Card
Small Time Crooks
Black Nativity
The Illusionist
Hachi: A Dog's Tale
Rounders
Le Havre
Monster
Four Lions
Forget Me Not
The Station Agent
Diamond Ruff
Pocketful of Miracles
Warcraft
Clash of the Titans
Volcano
Battle: Los Angeles
The Life Aquatic with Steve Zissou
The Missing Person
I Spit on Your Grave
In the Heart of the Sea
The Other Side of Heaven
Leatherheads
My Sister's Keeper
Abandon
Dirty Pretty Things
Black November
The Extra Man
Teeth and Blood
Theresa Is a Mother
The Good Heart
Poseidon
Blades of Glory
The Nut Job
Blade Runner
Bright Lights, Big City
The Adventures of Pinocchio
Crank: High Voltage
The November Man
Raising Cain
The Outsiders
Escape from Alcatraz
Desperado
City Island
Navy Seals vs. Zombies
Bound
The Perfect Wave
The Secret in Their Eyes
Ajami
Burn
A Dog's Breakfast
The Bourne Supremacy
The Monuments Men
Extreme Ops
Broken City
Moonlight Mile
New York Stories
The Assassin
Thirteen
ABCD (Any Body Can Dance)
Out of the Dark
Modern Times
Casablanca
Welcome to the Dollhouse
The Business of Fancydancing
The Night Visitor
Supporting Characters
Get Shorty
Wyatt Earp
Miss Congeniality 2: Armed and Fabulous
The Big Bounce
We're the Millers
Abduction
Repo Men
District 9
Mystery, Alaska
Schindler's List
Connie and Carla
Under the Tuscan Sun
The Boondock Saints
Layer Cake
Song One
No Escape
Trainspotting
Happy, Texas
Safe Men
Pierrot le Fou
The Mortal Instruments: City of Bones
Reservoir Dogs
Any Given Sunday
Thunder and the House of Magic
Bolt
The Secret Life of Walter Mitty
Oliver Twist
The Sentinel
Ronin
Licence to Kill
Atonement
Beyond the Sea
Hamlet
Saw: The Final Chapter
The Emperor's Club
The Boy in the Striped Pyjamas
Brother
Shopgirl
Bran Nue Dae
Light Sleeper
Spun
The Last Time I Committed Suicide
Fish Tank
River's Edge
Gangster Squad
Wish I Was Here
The Wraith
Fun with Dick and Jane
The Bourne Ultimatum
Gone in Sixty Seconds
Ben-Hur
As Good as It Gets
Supercross
Stealing Harvard
The Proposition
ATL
Arn: The Knight Templar
Wild Grass
Oculus
The Last Exorcism Part II
Compadres
Do You Believe?
Courageous
Mercy Streets
Facing the Giants
Open Secret
Killers
The Count of Monte Cristo
The Art of War
Texas Rangers
Max Payne
Four Brothers
Regression
Knockaround Guys
Crank
Killer Joe
Valley of the Wolves: Iraq
Boyz n the Hood
Butch Cassidy and the Sundance Kid
Kill the Messenger
Annie Hall
It's All Gone Pete Tong
The Bubble
Saw
Avengers: Age of Ultron
The Sorcerer's Apprentice
After Earth
Pocahontas
From Russia with Love
Niagara
The Firm
Black Rain
Never Back Down
Fugly
Swordfish
Ghost Rider: Spirit of Vengeance
A Million Ways to Die in the West
Precious
Hot Pursuit
The Untouchables
Veronica Guerin
Things We Lost in the Fire
Glengarry Glen Ross
Welcome to the Rileys
A Lonely Place to Die
Bella
Chernobyl Diaries
Dogtooth
Mission: Impossible II
22 Jump Street
Faster
Living Out Loud
Married Life
The Limey
The Raid
Spectre
Iron Man 3
Django Unchained
RED 2
Hard Rain
Blade: Trinity
Sin City: A Dame to Kill For
Kill Bill: Vol. 2
Law Abiding Citizen
The Bone Collector
Hero
The Talented Mr. Ripley
Unknown
The Hudsucker Proxy
Vampires
Double Impact
American Beauty
Halloween: Resurrection
City of Life and Death
The Red Violin
La Bamba
Khiladi 786
Shine
The Misfits
Thirteen Conversations About One Thing
Man on Wire
Nowhere Boy
The Lunchbox
Godzilla 2000
On the Outs
Captain America: The Winter Soldier
The Good German
Buffalo Soldiers
The Devil's Rejects
The Opposite Sex
R.I.P.D.
The Perfect Storm
The Rundown
U-571
Into the Blue
Jersey Girl
Inherent Vice
Pan's Labyrinth
Tidal Wave
Catch a Fire
The Sea Inside
The Postman Always Rings Twice
The Best Exotic Marigold Hotel
Live and Let Die
Bernie
Samsara
Purple Violets
Bully
Tiny Furniture
Spy Kids 2: The Island of Lost Dreams
Trade Of Innocents
High Crimes
Stranger Than Fiction
Legal Eagles
The Age of Innocence
A History of Violence
Step Up 3D
Flatliners
Legend
Jane Got a Gun
Reign Over Me
Loser
Bad Santa
The Corruptor
All Is Bright
Sholem Aleichem: Laughing In The Darkness
From Paris with Love
At First Sight
Barney's Version
The Greatest Story Ever Told
My All American
My Fair Lady
55 Days at Peking
Rachel Getting Married
End of the Spear
Melancholia
The Four Seasons
Sunshine State
Redacted
Water
To Kill a Mockingbird
Under the Same Moon
Antarctica: A Year on Ice
End of Days
Kung Fu Hustle
King Kong
The Hobbit: An Unexpected Journey
Æon Flux
Outbreak
Fled
Wicker Park
No Country for Old Men
Funny Games
For Your Consideration
Trade
A Walk to Remember
Frailty
The Work and the Glory
March or Die
To Write Love on Her Arms
The Legend of Drunken Master
Spider-Man 3
The Fugitive
Gothika
Kung Fu Panda 3
X2
Green Zone
Spy Game
Hotel for Dogs
First Knight
Lady in the Water
Wall Street: Money Never Sleeps
Dreamcatcher
Johnny English
Sweet Home Alabama
Heartbreakers
Love Happens
Where the Heart Is
Frida
Cyrus
Ca$h
Nowhere in Africa
Sunshine Cleaning
Ira & Abby
Repo Man
Alone With Her
American Hero
The Country Doctor
The Flowers of War
The Last Castle
Earth
Mandela: Long Walk to Freedom
Underclassman
The Naked Gun 2½: The Smell of Fear
The Book Thief
Fame
The Homesman
Chloe
The Namesake
Don McKay
The House of Sand
Chain of Command
The Timber
Northfork
Deterrence
The Birth of a Nation
TRON: Legacy
The Road to El Dorado
Unbreakable
The Mask of Zorro
Out of Time
Striptease
Babylon A.D.
The Skeleton Key
Million Dollar Baby
Wall Street
Jackie Brown
Quartet
Kinsey
Nicholas Nickleby
Stake Land
The Dog Lover
I Origins
Little Man
The Fifth Element
Braveheart
Murder by Numbers
Out of Sight
Morning Glory
War
I'm Not There.
Scream
Being Julia
Anything Else
If I Stay
Edmond
It's a Mad, Mad, Mad, Mad World
The I Inside
A Single Man
Platoon
Whale Rider
Mad Max: Fury Road
Evita
Red Cliff
Midnight Run
Kundun
Indignation
The Amityville Horror
Good
Love & Basketball
The Company
The Pursuit of D.B. Cooper
Shaolin Soccer
Beneath Hill 60
Glitter
Get Low
Rabbit-Proof Fence
The Heart of Me
The Hit List
Gandhi, My Father
Coming Home
This Thing of Ours
Housebound
Fast Five
Children of Men
The Green Mile
The Jackal
Resident Evil: Apocalypse
FearDotCom
Radio Flyer
Speed
The Curse of the Jade Scorpion
Psycho
Austin Powers: International Man of Mystery
This Christmas
Trust the Man
Driving Miss Daisy
Treading Water
Half Nelson
Bad Boys II
Me Before You
Dawn of the Planet of the Apes
The Saint
The Man from U.N.C.L.E.
Elizabethtown
Catch Me If You Can
A Time to Kill
City of Ember
Drag Me to Hell
The Transporter
About Time
The Words
Diary of a Mad Black Woman
Race
Hard Candy
The Broadway Melody
Resident Evil: Afterlife
Ride Along
The Pink Panther
Lucky Numbers
Paycheck
The Pacifier
The Game
Man on a Ledge
Gattaca
The Devil Wears Prada
United Passions
Birdman
Flicka
Kiss Kiss Bang Bang
Caravans
Paris, je t'aime
The Perks of Being a Wallflower
Oscar and Lucinda
The Wackness
Garden State
The Conversation
Orgazmo
Horse Camp
The Last Legion
Man on the Moon
Mickey Blue Eyes
Return to Oz
Suspect Zero
In the Land of Blood and Honey
Duma
What's Eating Gilbert Grape
The Visual Bible: The Gospel of John
Black or White
Igby Goes Down
Somewhere
Freeheld
Addicted
The Machinist
Blackthorn
The Secret
Diary of the Dead
The Last Five Years
The Act of Killing
The Jimmy Show
Bambi
The Young Unknowns
Tupac: Resurrection
Another Earth
Air Force One
Hollywood Homicide
Jonah Hex
John Q
Blue Jasmine
Smokin' Aces
Snatch
Body Double
A Man for All Seasons
Lake Mungo
On the Waterfront
Bullets Over Broadway
The Bank Job
The Barbarian Invasions
Thor: The Dark World
Wrath of the Titans
Alien: Resurrection
The Heat
Fifty Shades of Grey
The Hunting Party
Seed of Chucky
Flipper
What a Girl Wants
The Counselor
Zambezia
The Legend of the Lone Ranger
Admission
1982
They Will Have to Kill Us First
Mean Creek
Chuck & Buck
The Chronicles of Narnia: The Voyage of the Dawn Treader
The Soloist
Lucy
Goodbye Bafana
Mindhunters
Shadowlands
The Painted Veil
Letters from Iwo Jima
Insidious: Chapter 3
Hesher
90 Minutes in Heaven
Green Room
Driving Lessons
Futuro Beach
Escape from the Planet of the Apes
Brick Lane
The Rise of the Krays
Straight A's
Home Run
Bloody Sunday
The Incredibly True Adventure of Two Girls In Love
Shotgun Stories
Reality Show

In [47]:
import pickle

In [48]:
pickle.dump(new_df.to_dict,open('movies_dict.pkl','wb'))

In [49]:
import pickle
pickle.dump(new_df, open('movie_list.pkl', 'wb'))
pickle.dump(similarity, open('similarity.pkl', 'wb'))